### ISSUE TITLE
how can we send the customvars from the node.js module to the api ??

### ISSUE THREAD

**Issue by ghost** [MotionAI/nodejs-samples#3]

**Comment by WebMobi59** [comment]
hi, @ashishsurve21 
did you find the solution ?

**Comment by davidjnels** [comment]
I don't understand the question. customVars are passed in as "event.customVars" and you can do whatever you please with them.

**Comment by ghost** [comment]
Thanks for the help, but I already figured that out long back.


Thanks and Regards,
Ashish Surve
