### ISSUE TITLE
Stuck in the first trivia question and how to stop randomizing questions

### ISSUE THREAD

**Issue by raffylo** [MotionAI/nodejs-samples#6]
Hi, I used and Im attempting to edit the Trivia Bot which makes an API call to the Open Trivia, with the goal of making it retrieve questions instead from a text file in github. Technically, either a .txt or a .json does work (see github links below), but unfortunately, the quiz is stuck in the first question: 

![screenshot - with txt](https://user-images.githubusercontent.com/4143792/27854940-3e64d9de-619b-11e7-9e36-13c5d449c2dc.png)

https://raw.githubusercontent.com/raffylo/easy-trivia/master/easy-trivia.txt
https://raw.githubusercontent.com/raffylo/easy-trivia/master/easy-trivia.json

So how do i make the quiz progress to the next question? 

Next, which part of the code do I omit to remove randomizing the questions?

**Comment by davidjnels** [comment]
Have you read the docs? Set "continue" to true.

**Comment by raffylo** [comment]
David, sorry didnt work, setting it to true made the bot stop displaying the very next question.

**Comment by raffylo** [comment]
Hi David, its ok now, a Nodejs friend thinks he knows what code to punch in. Is there a way to delete this issue?
